### ISSUE TITLE
change to tsfcl required when cplflx=true for restart comparison tests

### ISSUE THREAD

**Issue by DeniseWorthen** [NOAA-EMC/ufsatm#105]
When cplflx is true, the values of tsfcl in the FV3 restart files fail the regression test comparisons because of values for tsfcl over ocean and ice. The tsfcl values over land are identical (when using CMEPS as the mediator).  For IPD, these changes are proposed at [LN 2069](https://github.com/DeniseWorthen/fv3atm/blob/2cdeafd30a3839bc6d256dc4a0031bf6131df982/gfsphysics/GFS_layer/GFS_physics_driver.F90#L2069) and at [LN 2077](https://github.com/DeniseWorthen/fv3atm/blob/2cdeafd30a3839bc6d256dc4a0031bf6131df982/gfsphysics/GFS_layer/GFS_physics_driver.F90#L2077). 

Equivalent changes need to be made on the CCPP side.

**Comment by climbfuji** [comment]
The IPD regression tests will be dropped in the next few weeks and the IPD development will be frozen very soon except for urgent bug fixes related to the GFSv16 implementation.

The corresponding CCPP code is in https://github.com/NCAR/ccpp-physics/blob/master/physics/GFS_surface_composites.F90 - please let me know if you need further information for making the changes there.

**Comment by DeniseWorthen** [comment]
Thanks Dom. The IPD change is in the FV3 branch I will be using for my PR for the CMEPS name changes which is why I created the issue to reference.  

For CCPP, is the equivalent change [here](https://github.com/NCAR/ccpp-physics/blob/20d7e9d687f0ec44d76a6c2b754a44a2fbbad0d9/physics/GFS_surface_composites.F90#L443) by inserting if(Model%cplflx)tsfcl = tsfc_ocn(i) and similarly for the ice covered areas?

**Comment by climbfuji** [comment]
> Thanks Dom. The IPD change is in the FV3 branch I will be using for my PR for the CMEPS name changes which is why I created the issue to reference.
> 
> For CCPP, is the equivalent change [here](https://github.com/NCAR/ccpp-physics/blob/20d7e9d687f0ec44d76a6c2b754a44a2fbbad0d9/physics/GFS_surface_composites.F90#L443) by inserting if(Model%cplflx)tsfcl = tsfc_ocn(i) and similarly for the ice covered areas?

Yes, this looks about right to me.

**Comment by DeniseWorthen** [comment]
I've been able to test this fix now on Cheyenne and it does pass our restart reproducibility test for tsfcl in the fv3 surface restart files.
