### ISSUE TITLE
snow depth over sea-ice

### ISSUE THREAD

**Issue by SMoorthi-emc** [NOAA-EMC/ufsatm#109]
This issue addresses a bug in the snow depth treatment within GFS when GFS is coupled to sea-ice model.  Sea-ice model exports snow volume, but radiation in GFS expects snow depth in mm.
Also, currently weasd (water equivalent snow depth) is set to zero over sea-ice.
While weasd is simply a diagnostic, the snow albedo over sea ice could have significant role in polar climate.  The update will be in sfc_cice.f.  I appears that snow volume in cice is defined as ice_fraction*snow depth; if this is correct then the snow depth passed to radiation should have snow volume / ice_fraction (this is what I am assuming for now unless ice experts can convince me otherwise).

**Comment by DeniseWorthen** [comment]
Your understanding is how I also understand it. The snow thickness in the ice-covered part of the grid cell is given by snow_volume/ice_fraction.

Will you also be working on bringing CICE's exported albedos into the radiation scheme?

**Comment by SMoorthi-emc** [comment]
Great, I feel more comfortable with what I did.
Right now radiation uses this information in modifying albedo.
We could use albedo from CICE, but it is a bit complicated, particularly with ccpp.
I still haven't figured out why I can't reproduce with restart.

**Comment by climbfuji** [comment]
> Great, I feel more comfortable with what I did.
> Right now radiation uses this information in modifying albedo.
> We could use albedo from CICE, but it is a bit complicated, particularly with ccpp.
> I still haven't figured out why I can't reproduce with restart.

Hi Moorthi, this is how I do this: add a call to scheme GFS_diagtoscreen and GFS_interstitialtoscreen in the radiation group (after GFS_interstitial_rad_reset) and in the physics group (after GFS_suite_stateout_reset).

Choose a small test case (C96?) that you can run with very few MPI tasks (6 for the compute of the atmosphere, i.e. one per tile). Set layout=1,1 in input.nml and blocksize=2304 (for example, this means 4 blocks per task; use 9216 if you want only one block per task). Then also make sure that every task writes out the time step information, i.e., in atmos_model.F90, replace
```
      if (mpp_pe() == mpp_root_pe()) write(6,*) "---isec,seconds",isec,seconds
```
with
```
      write(6,*) "---isec,seconds",isec,seconds
      write(0,*) "---isec,seconds",isec,seconds
```
Then run a 2h forecast in one directory, a 1h cold start in another, and a 1h->2h warmstart in a third directory taking the restart files from the 1h cold start as input.

Then compare the output in out and err between the 2h run and the 1h->2h warmstart run (throw away the output from the first hour of the full 2h run).

**Comment by SMoorthi-emc** [comment]
Dom,
   I assume your suggestion is about the restart issue that I am having.  The way I am doing it is slightly different.
I am looking at results from every time step.  After I restart, the first two time steps are identical, but the thiird time step is not.   Differences are in a few fields, only a few bits different.  Fields from ice to atm are identical.  Differences are in sensible heat flux at one  or two points at the precision level.
That is the reason I have been updating the code to update precision properly.  I am also finding small differences in dzdt.  The differences don't appear to be from the coupling, although, the uncoupled model reproduces.

**Comment by climbfuji** [comment]
> Dom,
> I assume your suggestion is about the restart issue that I am having. The way I am doing it is slightly different.
> I am looking at results from every time step. After I restart, the first two time steps are identical, but the thiird time step is not. Differences are in a few fields, only a few bits different. Fields from ice to atm are identical. Differences are in sensible heat flux at one or two points at the precision level.
> That is the reason I have been updating the code to update precision properly. I am also finding small differences in dzdt. The differences don't appear to be from the coupling, although, the uncoupled model reproduces.

I see. At least, the GFS_diagtoscreen gives you min / max / 32-bit Adler Checksum of each array, I assume that there are tiny differences in the first two timesteps already, but you only see them when you compute the checksum. Just a guess, though.

**Comment by DeniseWorthen** [comment]
Moorthi,

If you point me to your FV3 branch and what options I might need to change in the input.nml, I could try out your FV3 in our repro test on Cheyenne using CMEPS. If it passed, then that to me would indicate a NEMS mediator issue; if it didn't that would indicate an FV3 issue.

**Comment by SMoorthi-emc** [comment]
Denise, thanks.
I just found some issue with my FV3 branch.  Let me see if that works.
If not I will merge with latest FV3 develop and then let you know my branch.

**Comment by SMoorthi-emc** [comment]
While the following is not relevant to this issue, I am glad to announce that my restart run now reproduces the continuous run, even with nsst model turned on with NEMS Mediator.

**Comment by DeniseWorthen** [comment]
BRAVO!

**Comment by junwang-noaa** [comment]
This was committed in FV3 PR #155, close issue.
