### ISSUE TITLE
Recommended changes / cleanup work for PR https://github.com/NOAA-EMC/fv3atm/pull/134

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/ufsatm#137]
The code review of https://github.com/NOAA-EMC/fv3atm/pull/134 highlighted some changes to be made in the next commits and some areas of investigation.

gfsphysics/GFS_layer/GFS_typedefs.meta, line 4077: addition of variable `cycling` - is this really required or does the model have the capability that @joeolson42 was seeking for the MYNN PBL/SFC physics?

gfsphysics/GFS_layer/GFS_typedefs.F90, line 5809: is variable `i` required? If not, remove.

gfsphysics/GFS_layer/GFS_typedefs.F90, line 5786: is variable `i` required? If not, remove.

gfsphysics/GFS_layer/GFS_diagnostics.F90, line 2628 and other places: for tendency from non-physics processes, maybe it's good not to put it in "gfs_phys" model in the future

**Comment by climbfuji** [comment]
@junwang-noaa instead of "gfs_phys", what would be the correct mod_name to use for outputting the non-physics tendencies? Does "gfs_dyn" exist?

**Comment by climbfuji** [comment]
@joeolson42 I am trying to address the comment about the newly added "cycling" variable for MYNN PBL. I see in `FV3/ccpp/physics/physics/module_bl_mynn.F90` that the `restart` and `cycling` flags have nearly (but not entirely) the same effect:
```
    LOGICAL, INTENT(in) :: restart,cycling
...
       IF ( (restart .or. cycling)) THEN
...
       if (.not.restart .or. .not.cycling) THEN
...
```
In `GFS_typedefs.{F90,meta}` I see that `cycling` is set to `.false.` by default and never changed to `.true.`, not even for the `fv3_ccpp_gsd_warmstart` runs (there, `restart` is set to `.true.`).

So I am wondering if we could, for the purpose of the integration in the UFS while keeping the lower-level module `FV3/ccpp/physics/physics/module_bl_mynn.F90` unchanged for use with WRF etc, make `cycling` a local variable, hardcoded to `.false.` in `ccpp/physics/physics/module_MYNNPBL_wrapper.F90` and remove it from `GFS_typedefs.{F90,meta}` and `module_MYNNPBL_wrapper.meta`?

If we really need to expose the `cycling` variable through the CCPP at a later stage for use with other models (or because the restart capability of the UFS turns out to be insufficient), we can always revert this change.

@junwang-noaa what is your take on this?

**Comment by junwang-noaa** [comment]
That makes sense to me.

**Comment by climbfuji** [comment]
Everything except moving the non-physics tendencies out of the `gfs_phys` stream was addressed in https://github.com/NOAA-EMC/fv3atm/pull/140.

**Comment by climbfuji** [comment]
The remaining issue `gfs_phys` vs . `gfs_dyn` is also covered here, with more information: https://github.com/NOAA-EMC/fv3atm/issues/159. Everything else was addressed, closing.
