### ISSUE TITLE
Initializing non-zero ice fluxes in the cold coupled run with CMEP

### ISSUE THREAD

**Issue by ShanSunNOAA** [NOAA-EMC/ufsatm#142]
Currently dusfci_cpl, dvsfci_cpl, dtsfci_cpl and dqsfci_cpl are initialized by values from PBL in the cold run at the 1st time step, which happens to be flag_cice=F for NEMS. However, "flag_cice" is not the right flag for "1st time cold run" in the case of CMEPS. We replaced the flag_cice condition by dusfcin_cpl, i.e., when ice flux is huge (undefined), use PBL-calculated ice fluxes instead. This will change results in the coupled model only. Passed regression tests for standalone FV3.

This needs to go with ccpp-physics #472.

**Comment by climbfuji** [comment]
@shansun6 will this be fixed by https://github.com/NCAR/ccpp-physics/pull/563 ?

**Comment by ShanSunNOAA** [comment]
Yes it is the same thing but at a higher FV3atm level. My misunderstanding
for creating an issue there as well.

Thanks,
Shan

**Comment by climbfuji** [comment]
This will be fixed in https://github.com/NCAR/ccpp-physics/pull/563.
