### ISSUE TITLE
Add support for GEFS-Aerosols restart capability

### ISSUE THREAD

**Issue by rmontuoro** [NOAA-EMC/ufsatm#15]
The following minor changes to FV3's coupling infrastructure are required to support bit-for-bit restart capability for GEFS-Aerosols:

- GSDCHEM, the coupled chemistry component in GEFS-Aerosols, uses precipitation tendencies computed as differences between FV3 accumulated precipitations at consecutive coupling steps.
Accumulation always begins at startup, whether the model is restarting or cold starting, introducing roundoff errors that lead to precipitation tendencies not being identical between a cold start run and a restart run. Coupling accumulation arrays for large-scale and convective rain, as well as snow, need to be reset to zero at every coupling step.

- FV3's instantaneous total moisture tendency coupling array will also need to be reset to zero at the beginning of each coupling step when coupling with GSDCHEM.

**Comment by junwang-noaa** [comment]
Raffaele,

Would you please list the code changes in fv3atm here so that we can add it to the branch for commit? Thanks.

**Comment by junwang-noaa** [comment]
I see it, thanks.

**Comment by rmontuoro** [comment]
@junwang-noaa, a description of the code changes in fv3atm is provided in issue #15 and #16 (see also PR #17)

**Comment by junwang-noaa** [comment]
I see it, thanks. I am adding the code changes to the commit branch and expecting no impact on ufs-weather-model. Thanks.

**Comment by junwang-noaa** [comment]
Code is committed.
