### ISSUE TITLE
Bug fixes in support of FV3GFS-AQM

### ISSUE THREAD

**Issue by rmontuoro** [NOAA-EMC/ufsatm#16]
The following bugs were discovered during development work for the coupled FV3GFS-CMAQ system (FV3GFS-AQM):

- Floating invalid errors are generated due to uninitialized optical depth diagnostic arrays (0.55 and 10 um channels). The code needs to be refactored.

- The canopy resistance output variable needs to be initialized to zero in the Noah/OSU land-surface model sub driver. This is required for FV3GFS-AQM as this quantity is passed to AQM (CMAQ) during coupling.

**Comment by junwang-noaa** [comment]
Code is committed.
