### ISSUE TITLE
Adding coupled suite files for v16 physics

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/ufsatm#194]
## Description
Want to run the coupled model with GFSv16 physics. @SMoorthi-emc said this requires an additional line: 
`      <scheme>sfc_cice</scheme>
`
not already in the existing suite files. 

## Solution
Add two new suite definition files, one for NSST (suite_FV3_GFS_v16beta_couplednsst.xml) and one for no NSST (suite_FV3_GFS_v16beta_coupled.xml) are needed.   Branch with these updates is here: https://github.com/JessicaMeixner-NOAA/fv3atm/tree/feature/gfsv16suites4coupled

## Alternatives
This could replace an existing coupled suite file (although the new name would probably be better) so that there are not too many coupled suite files.  The names could change if there is a preference for something different. 

## Testing:

At this point no testing as been completed.  A regression test should at some point be added using this physics options for the coupled model.

**Comment by climbfuji** [comment]
Closed via https://github.com/NOAA-EMC/fv3atm/pull/202.
