### ISSUE TITLE
release/public-v2: Update SDFs with correct version number

### ISSUE THREAD

**Issue by ligiabernardet** [NOAA-EMC/ufsatm#195]
The version number in the Suite Definition Files is set to 4. It should be set to 5, for compatibility with the CCPP v5 release.

Files suite_FV3_GFS_v15p2.xml and suite_FV3_RRFS_v1beta.xml: change ver="4" to ver="5".

**Comment by climbfuji** [comment]
Closed via https://github.com/NOAA-EMC/fv3atm/pull/197.
