### ISSUE TITLE
Implement high-frequency outputs in coupled runs and  test coupled options with NSST and without NSST

### ISSUE THREAD

**Issue by JoshuaFu-NOAA** [NOAA-EMC/ufsatm#203]
## Description
Provide a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## Solution
Add a clear and concise description of what solution you provide.

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Testing:

1. Have you tested the code changes? On what platforms?
2. Have you run regression test in ufs-weather-model or ufs-s2s-model with code changes?
- Will the baseline results change?
- If yes, please give brief explanation of your code updates on the regression test.

## Dependent PRs:

Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/GFDL_atmos_cubed_sphere/issues/<issue_number>
- ncar/ccpp-physics/pull/<pr_number>
- associated ufs-weather-model/pull/<pr_number>

**Comment by climbfuji** [comment]
@JoshuaFu-NOAA please update the description of the issue with the relevant information so that we know better what needs to be done, which repositories will be affected etc. Thanks.

**Comment by junwang-noaa** [comment]
Since it is not clear what needs to be done in this issue, let's close it. We can open a new issue with detailed information if there is any request from coupled group.
