### ISSUE TITLE
Duplicate symbols on macOS with Intel

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/ufsatm#206]
I'm getting duplicate symbols on macOS building with Intel 2021.1

I encountered this bug (different files) a few months ago which was fixed with https://github.com/NOAA-EMC/fv3atm/pull/173 (`gfsphysics/CMakeLists.txt`)

The problem is that `noahmp_tables.f90`, `CCPP_data.F90`, and `namelist_soilveg.f` are being built twice. Once in `CCPP_SOURCES` and once in `IPD_SOURCES` and then their symbols conflict when linked at the end. 

https://github.com/NOAA-EMC/fv3atm/blob/a898cca15f8c3bdcc2c6d30de1e4bbe1ed9da110/gfsphysics/CMakeLists.txt#L19

This issue reared its head because of a change I had to make in the weather model's CMakeLists because I was getting undefined symbols with Intel + macOS.

I had to add this line to fix the undefined symbols, but as a side-effect the symbols in the aforementioned files now conflict: 

```
if(APPLE)
  # The linker on macOS does not include `common symbols` by default
  # Passing the -c flag includes them and fixes an error with undefined symbols
  set(CMAKE_Fortran_ARCHIVE_FINISH "<CMAKE_RANLIB> -c <TARGET>")
endif()
```

See: https://github.com/ufs-community/ufs-weather-model/issues/309

This shows up with Intel and not GCC because they handle uninitialized module variables differently. Intel marks them as `C` (common) symbols (which aren't included by default by macOS's linker), but GCC marks them as `S` (uninitialized data section for small objects).

**Comment by climbfuji** [comment]
See here https://github.com/ufs-community/ufs-weather-model/issues/309#issuecomment-737000252 please.

**Comment by climbfuji** [comment]
This will be fixed by https://github.com/NOAA-EMC/fv3atm/pull/249.
