### ISSUE TITLE
One NSST model  constant change and the inclusion of the ccpp/physics submodule change

### ISSUE THREAD

**Issue by XuLi-NOAA** [NOAA-EMC/ufsatm#219]
## Description
Reduce the initialized warm layer thickness to be 20 m when the NSST model is cold start in FV3 io. 
Add one ccpp suite: suite_FV3_GFS_v15p2_couplednsst.xml
Include the change in ccpp/physics submodule (see https://github.com/NCAR/ccpp-physics/issues/537).

**Comment by junwang-noaa** [comment]
Xu, can we close this issue? Thanks

**Comment by XuLi-NOAA** [comment]
Yes, thanks!
