### ISSUE TITLE
The new suite FV3_GFS_v16b_ugwpv1 for GFSv16b-127L/C96 to work on issue #347 in ufs-weather-model                                 

### ISSUE THREAD

**Issue by ValeryYudin-NOAA** [NOAA-EMC/ufsatm#222]
## Description
The new CCPP suite FV3_GFS_v16b_ugwpv1 and regression tests for warm_start and cold_starts
with GFSv16b (low resolution, C96_L127). The new suite represents the upgrade of uGWP (V1),CU-CIRES. It is capable to reproduce the realistic FV3GFS climate, including equatorial dynamics (QBO and SAO, 20-60 km)) and annual cycles in the extra-tropics and polar regions in the upper atmsosphere (20-80km). It can be executed and tested with the gsldrag sub-grid scale orography physics of gsl/develop for UFS-R2O planned activity in 2021.

## Solution
Under FV3/ccpp 
a) add corresponding suite 
 FV3/ccpp/suites/suite_FV3_GFS_v16b_ugwpv1.xml
and
b)  modify  FV3/ccpp/config/ccpp_prebuild_config.py
Under FV3/gfsphysics/GFS_layer:
     modify GFS_typedefs.F90  GFS_typedefs.meta 
## Alternatives
N/A

## Testing:

1. Have you tested the code changes? On what platforms?
Hera/Intel
2. Have you run regression test in ufs-weather-model or ufs-s2s-model with code changes? -Yes in ufs-werather-model
- Will the baseline results change -Yes
- If yes, please give brief explanation
  The physically-motivated RT tests for warm and cold starts of UFS-127L/C96 have been created that corresponds
  to the low-resolution runs of GFSv16

## Dependent PR/Issues:
NCAR/ccpp-physics #issue 542
ufs-weather-model: #issue  347

**Comment by climbfuji** [comment]
Closed via https://github.com/NOAA-EMC/fv3atm/pull/241.
