### ISSUE TITLE
Cleanup of FV3GFS_io.F90

### ISSUE THREAD

**Issue by ShanSunNOAA** [NOAA-EMC/ufsatm#226]
Removing print statements in FV3GFS_io.F90: Lines 1082-1084; 1087-1088; 1096-1098; 1101-1102.  No change in results.

**Comment by climbfuji** [comment]
@shansun6 since the line numbers have changed, can you please provide the line numbers based on hash 116d701
 of the fv3atm repository?

**Comment by ShanSunNOAA** [comment]
In FV3GFS_io.F90 of hash 116d701, please remove these lines below. Thanks. 

   1067               if (Sfcprop(nb)%slmsk(ix) < 1.9_r8)      &
   1068                 write(*,'(a,2i3,3f6.2)') 'reset lake slmsk=2 at nb,ix=' &
   1069                ,nb,ix,Sfcprop(nb)%fice(ix),Sfcprop(nb)%slmsk(ix),Sfcprop(nb)%lakefrac(ix)

   1072                 write(*,'(a,2i3,3f6.2)') 'reset lake slmsk=0 at nb,ix=' &
   1073                ,nb,ix,Sfcprop(nb)%fice(ix),Sfcprop(nb)%slmsk(ix),Sfcprop(nb)%lakefrac(ix)

   1081               if (Sfcprop(nb)%slmsk(ix) < 1.9_r8)      &
   1082                 write(*,'(a,2i3,3f6.2)') 'reset sea slmsk=2 at nb,ix=' &
   1083                ,nb,ix,Sfcprop(nb)%fice(ix),Sfcprop(nb)%slmsk(ix),Sfcprop(nb)%landfrac(ix)

  1086                 write(*,'(a,2i3,4f6.2)') 'reset sea slmsk=0 at nb,ix=' &
  1087                ,nb,ix,Sfcprop(nb)%fice(ix),Sfcprop(nb)%slmsk(ix),Sfcprop(nb)%landfrac(ix)
