### ISSUE TITLE
bug in gfsphysics/physics/moninedmf_hafs.f

### ISSUE THREAD

**Issue by grantfirl** [NOAA-EMC/ufsatm#24]
When the namelist option dspheat = True, the energy from turbulence dissipation is added to the heating rate from the hybrid EDMF PBL scheme. In the version modified for the HAFS application (gfsphysics/physics/moninedmf_hafs.f), a different hard-coded value is used to apply this heating (0.7 vs 0.5). This change is supposed to apply to all model levels, but as coded, the change is only applied to the lowest model level. See line 1363. It should be done like lines 1349-1353 as in module_bl_gfsedmf.F of the HWRF code. 

(Line numbers correspond to commit #8a567812866a80d8320ecb8d946c894a91c8047c)

Note that this error has been addressed in the merged moninedmf.f + moninedmf_hafs.f in the CCPP (see https://github.com/NCAR/ccpp-physics/pull/370).

**Comment by grantfirl** [comment]
@BinLiu-NOAA @ChunxiZhang-NOAA
Weiguo Wang has been notified of the issue too.

**Comment by junwang-noaa** [comment]
Code is committed, close the issue.
