### ISSUE TITLE
fix bug in ugwd

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-EMC/ufsatm#26]
Velary and hist team reported two buges to Fanglin:

1) [Jun.Wang@m72a2 FV3]$ git diff 8a567812 gfsphysics/GFS_layer/GFS_driver.F90
diff --git a/gfsphysics/GFS_layer/GFS_driver.F90 b/gfsphysics/GFS_layer/GFS_driver.F90
index 3b6a943..05f97bd 100644
--- a/gfsphysics/GFS_layer/GFS_driver.F90
+++ b/gfsphysics/GFS_layer/GFS_driver.F90
@@ -422,7 +422,7 @@ module GFS_driver
       call cires_ugwp_init(Model%me,      Model%master, Model%nlunit,  Init_parm%logunit, &
                            Model%fn_nml,  Model%lonr,   Model%latr,    Model%levs,        &
                            Init_parm%ak,  Init_parm%bk, p_ref,         Model%dtp,         &
-                           Model%cdmbgwd, Model%cgwf,   Model%prslrd0, Model%ral_ts)
+                           Model%cdmbgwd(1:2), Model%cgwf,   Model%prslrd0, Model%ral_ts)
     endif
 #endif

2) [Jun.Wang@m72a2 FV3]$ git diff 8a567812 gfsphysics/physics/ugwp_driver_v0.f
diff --git a/gfsphysics/physics/ugwp_driver_v0.f b/gfsphysics/physics/ugwp_driver_v0.f
index 804bbac..0ca37e8 100644
--- a/gfsphysics/physics/ugwp_driver_v0.f
+++ b/gfsphysics/physics/ugwp_driver_v0.f
@@ -46,7 +46,9 @@
      &,                            rain

        real(kind=kind_phys), intent(in), dimension(im,levs) :: ugrs
-     &,        vgrs, tgrs, qgrs, prsi, prsl, prslk, phii, phil, del
+     &,        vgrs, tgrs, qgrs, prsl, prslk, phil, del
+       real(kind=kind_phys), intent(in), dimension(im,levs+1) :: prsi
+     &,        phii

**Comment by climbfuji** [comment]
These bugs are fixed in the PR for ufs_public_release (https://github.com/NOAA-EMC/fv3atm/pull/22) and will be fixed with the follow-up PR from DTC to the develop branch.

**Comment by SMoorthi-emc** [comment]
GWD updates look ok

**Comment by junwang-noaa** [comment]
Code is committed.
