### ISSUE TITLE
Surface instability over fractional grid

### ISSUE THREAD

**Issue by ShanSunNOAA** [NOAA-EMC/ufsatm#260]
From weizhong.zheng@noaa.gov

Numerical instability associated with super high surface temperature over a fractional grid, which was first seen at the southeast coast of Australia. A more physical implementation of the surface layer scheme is under development.

**Comment by junwang-noaa** [comment]
@shansun6 I think this issus is resolved with the [PR#285](https://github.com/NOAA-EMC/fv3atm/pull/285), can we close the issue?

**Comment by ShanSunNOAA** [comment]
Yes, it has been resolved. Please close this issue. Thanks,

Shan
