### ISSUE TITLE
update fv3atm for esmf bs47

### ISSUE THREAD

**Issue by DeniseWorthen** [NOAA-EMC/ufsatm#265]
## Description
The coupled application is currently using esmf bs27. To update to a later bs47 changes are required in fv3atm.

## Solution

Changes are required in cpl/module_cap_cpl.F90 and fv3_cap.F90

## Testing:

Testing on hera.intel and wcoss-dell-p3 show comparison failures for these tests and files (all other files pass either alt or direct comparison):

fv3_regional_quilt: NATLEV.GrbF00 and NATLEV.GrbF24
fv3_esg_HAFS_v0_hwrf_thompson and fv3_esg_HAFS_v0_hwrf_thompson_debug : phyf000 and dynf000

See ufs-weather-model PR [#493](https://github.com/ufs-community/ufs-weather-model/pull/493)

**Comment by DusanJovic-NOAA** [comment]
Any particular reason why esmf bs47 instead of esmf 8.1.0, which was released yesterday?

**Comment by DeniseWorthen** [comment]
No, probably not. It has been tested at bs47 but could be tested at 8.1.0 if it was available in the stacks.
