### ISSUE TITLE
Reduce number of CCPP suites after ufs-weather-model regression test update

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/ufsatm#282]
## Description

We currently (2021/04/15) have 68 suites in FV3's `ccpp/suites` directory. It is tedious to make changes to CCPP schemes that then require changing each suite definition file.

## Solution

After the update of the ufs-weather-model regression tests has been completed, I suggest:

1. Identify which suites are used by the regression tests, keep those.
2. For the remaining suites, identify owners and whether these suites are still actively used in development and testing by those individuals or collaborators. If yes, keep, if no, delete.
3. Rinse and repeat every year.

## Alternatives
Let the number of suite definition file grow and grow. 

## Testing:

n/a

## Dependent PRs:

n/a

**Comment by climbfuji** [comment]
As of 2021/08/02, we have 80 suites in directory `ccpp/suites`. The ufs-weather-model regression tests use 41 of these. I believe that some of the following suites that are not used can be deleted. I would like to ask the physics developers and fv3atm code managers to help me identify which suites are no longer needed. @yangfanglin @SMoorthi-emc @junwang-noaa @DusanJovic-NOAA @ligiabernardet

I created a spreadsheet to keep track of what to keep and delete, this is the link to VIEW the spreadsheet: https://docs.google.com/spreadsheets/d/1oDF_L1pkt-J1engAnD431FhE-q09XtZ78LvrT4wZ1Y8/edit?usp=sharing

If you want edit/comment access, please let me know. Thanks!

> Suite FV3_CPT_v0 NOT used
> Suite FV3_GFS_2017 NOT used
> Suite FV3_GFS_2017_coupled NOT used
> Suite FV3_GFS_2017_couplednsst NOT used
> Suite FV3_GFS_2017_csawmg NOT used
> Suite FV3_GFS_2017_gfdlmp NOT used
> Suite FV3_GFS_2017_gfdlmp_noahmp NOT used
> Suite FV3_GFS_2017_gfdlmp_regional NOT used
> Suite FV3_GFS_2017_h2ophys NOT used
> Suite FV3_GFS_2017_ozphys_2015 NOT used
> Suite FV3_GFS_2017_sas NOT used
> Suite FV3_GFS_2017_satmedmf NOT used
> Suite FV3_GFS_2017_satmedmf_coupled NOT used
> Suite FV3_GFS_2017_satmedmfq NOT used
> Suite FV3_GFS_cpld_rasmgshoc NOT used
> Suite FV3_GFS_cpld_rasmgshocnsst NOT used
> Suite FV3_GFS_cpld_rasmgshocnsst_flake NOT used
> Suite FV3_GFS_cpldnst_rasmgshoc NOT used
> Suite FV3_GFS_rasmgshoc NOT used
> Suite FV3_GFS_v15 NOT used
> Suite FV3_GFS_v15_ras NOT used
> Suite FV3_GFS_v15_rasmgshoc NOT used
> Suite FV3_GFS_v15_thompson NOT used
> Suite FV3_GFS_v15_thompson_mynn_lam3km NOT used
> Suite FV3_GFS_v15p2 NOT used
> Suite FV3_GFS_v15p2_RRTMGP NOT used
> Suite FV3_GFS_v15p2_coupled NOT used
> Suite FV3_GFS_v15p2_couplednsst NOT used
> Suite FV3_GFS_v15p2_no_nsst NOT used
> Suite FV3_GFS_v15plus NOT used
> Suite FV3_GFS_v15plusras NOT used
> Suite FV3_GFS_v16_coupled_nsstNoahmp NOT used
> Suite FV3_GFS_v16_no_nsst NOT used
> Suite FV3_GFSv17alpha_cpldnsstras NOT used
> Suite FV3_GFSv17alpha_cpldnsstras_flake NOT used
> Suite FV3_GFSv17alpha_cpldnsstrasnoshal NOT used
> Suite FV3_GFSv17alpha_cpldnsstsas NOT used
> Suite FV3_GFSv17alpha_ras NOT used
> Suite FV3_GFSv17alpha_ras_flake NOT used
> Suite FV3_GFSv17alpha_sas NOT used
> Suite FV3_GSD_v0_unified_ugwp_suite_noah NOT used

**Comment by yangfanglin** [comment]
Dom,  when you say the following suites that are not used can be deleted, do you mean they are not used by any of the regression tests ?   Can you give all access the spreadsheet to make comments ?

**Comment by SMoorthi-emc** [comment]
What is the harm in keeping SDFs?
Considering that CCPP requires different SDF to turn on different physics options we should encourage having more SDF not less.
I am very disappointed with thought of having to remove SDF. This is not helping community modeling.
Sorry, I don’t endorse this.
Moorthi

**Comment by climbfuji** [comment]
> Dom, when you say the following suites that are not used can be deleted, do you mean they are not used by any of the regression tests ? Can you give all access the spreadsheet to make comments ?

Yes, they are not used by any of the regression tests. I know that several suites should be kept for testing by our developers, but there are several that won't be used anymore (I would assume some of the old GFS v14 suites). This is why I created the spreadsheet so that we can gather information. It's open for commenting for all NOAA folks.

**Comment by climbfuji** [comment]
> What is the harm in keeping SDFs? Considering that CCPP requires different SDF to turn on different physics options we should encourage having more SDF not less. I am very disappointed with thought of having to remove SDF. This is not helping community modeling. Sorry, I don’t endorse this. Moorthi
> […](#)

Please see my reply to Fanglin. I think there are several suites that are really no longer in use, for example `FV3_CPT_v0` or some of the older GFS v14 variants. I am not saying we should remove suites that people are experimenting with (although a point can be made that these could be kept in user forks, but I know this is cumbersome and therefore prefer not to go this way).

But please keep in mind that the more suites you have, the more housekeeping is needed. And it would be nice if we could compile all suites (by not specifying the argument `CCPP_SUITES=...`). This still works with GNU, but no longer with Intel (internal compiler error, tries to optimize too much). It used to work with Intel when we had about 40 suites or so.

**Comment by climbfuji** [comment]
@DeniseWorthen Last I remember you were trying to work on that using the spreadsheet https://docs.google.com/spreadsheets/d/1oDF_L1pkt-J1engAnD431FhE-q09XtZ78LvrT4wZ1Y8/edit?usp=sharing. Can you remind me about the current status, please?

**Comment by DeniseWorthen** [comment]
@climbfuji I am planning on removing ``FV3_GFS_2017_coupled`` and ``suite_FV3_GFS_2017_satmedmf_coupled.xml``. I can't do this until the PR #765 has been committed.

**Comment by arunchawla-NOAA** [comment]
@climbfuji 

can we close this issue ? the PR associated with this issue is already closed

**Comment by climbfuji** [comment]
Yes ... I am declaring defeat on my overly ambitious goal of really reducing the number of suites ;-)
