### ISSUE TITLE
Shall I add doxygen to the build system?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/ufsatm#289]
Shall I add doxygen to the build system, which would allow programmers to start using doxygen in the code?

**Comment by junwang-noaa** [comment]
Yes, it is good to have it in the build system.

**Comment by edwardhartnett** [comment]
This is being held back by the lack of self-build capability in fv3atm. We can't do a doxygen build in CI if fv3atm cannot even be compiled successfully in CI.

**Comment by edwardhartnett** [comment]
I will close this issue until there is greater interest, and a fixed build system.

**Comment by edwardhartnett** [comment]
OK, interest in testing fv3atm has led to interest in documentation too.

The problems start because of the way we're lumping so many projects together using git submodules, rather than releasing them as separate libraries and then linking them in the usual way.

For example, the doc build of fv3atm will not work because both ccpp and upp include a "doc" target in their cmake files.

```
CMake Error at upp/docs/CMakeLists.txt:10 (add_custom_target):
  add_custom_target cannot create target "doc" because another target with
  the same name already exists.  The existing target is a custom target
  created in source directory
  "/home/runner/work/fv3atm/fv3atm/fv3atm/ccpp/framework/doc".  See
  documentation for policy CMP0002 for more details.


```
See https://github.com/edwardhartnett/fv3atm/actions/runs/7371629648/job/20059198642?pr=2
