### ISSUE TITLE
Physics update in cumulus convection, PBL & surface layer for UFS_P7

### ISSUE THREAD

**Issue by JongilHan66** [NOAA-EMC/ufsatm#299]
## Description
1) Cumulus convection
     a) More strict convection trigger 
     b) Reduced entrainment rate below cloud base
     c) Enhanced downdraft detrainments starting from 60mb above the ground surface
     d) Reduced rain evaporation
     e) Modification of cloud depth separating shallow convection from deep convection
2) PBL and surface layer
    a) Inclusion of wind shear effect reducing characteristic mixing length
    b) Reduction of background diffusivity in the inversion layers as a function of surface roughness and green vegetation fraction
    c) PBL updraft overshooting limited by bulk Richardson number-based-PBL depth
    d) Inclusion of new canopy heat storage parameterization  
    e) Modification of thermal roughness calculation over land
    f) Increase of momentum roughness length over sea
    g) Inclusion of sea spray effect parameterization

The verification results for the physics updates above can be found in https://www.emc.ncep.noaa.gov/gmb/jhan/vsdbw/ccaa14
More detailed description for the updates and ccaa14 results are given in the attached ppt file.

Verification results for additional physics updates are in:
 1) Increased sea spray effects: https://www.emc.ncep.noaa.gov/gmb/jhan/vsdbw/ccaa27
 2) Inclusion of new maximum z/L parameterization in the GFS surface layer scheme:
    Winter: https://www.emc.ncep.noaa.gov/gmb/jhan/vsdbw/ccaa41
    Summer: https://www.emc.ncep.noaa.gov/gmb/jhan/vsdbw/ccaa41x

The final update is based on 'ccaa41'

[Tests_physics_MRF_MJO_JHan_WLi.pptx](https://github.com/NOAA-EMC/fv3atm/files/6468546/Tests_physics_MRF_MJO_JHan_WLi.pptx)

.

Provide a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## Solution
Add a clear and concise description of what solution you provide.

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Testing:

1. Have you tested the code changes? On what platforms?
2. Have you run regression test in ufs-weather-model or ufs-s2s-model with code changes?
- Will the baseline results change?
- If yes, please give brief explanation of your code updates on the regression test.

## Dependent PRs:

Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/GFDL_atmos_cubed_sphere/issues/<issue_number>
- ncar/ccpp-physics/pull/<pr_number>
- associated ufs-weather-model/pull/<pr_number>

**Comment by JongilHan66** [comment]
Description for the new maximum z/L parameterization can be found in the attached ppt file
[PBL_SL_inv_JHan.pptx](https://github.com/NOAA-EMC/fv3atm/files/6468850/PBL_SL_inv_JHan.pptx)

**Comment by junwang-noaa** [comment]
The code was committed in PR #314, close issue
