### ISSUE TITLE
Updates to cellular automaton scheme 

### ISSUE THREAD

**Issue by lisa-bengtsson** [NOAA-EMC/ufsatm#304]
Updates include:

1) Introduction of CA domain definition.
2) Read/Write and restart capability of CA
3) Significant cleaning of old ideas
4) Improved coupling to cumulus convection to be committed in coordination with this issue: NCAR/ccpp-physics#657

Test results with GFSv16 as a baseline (atmosphere only) can be found here: https://www.emc.ncep.noaa.gov/gmb/jhan/vsdbw/v16upcas2/ and https://www.emc.ncep.noaa.gov/gmb/jhan/vsdbw/v16upcaw2

https://github.com/noaa-psd/stochastic_physics/issues/40

**Comment by junwang-noaa** [comment]
The code updates were committed on PR#305, close issue.
