### ISSUE TITLE
Remove scheme `rayleigh_damp` from all suite definition files

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/ufsatm#340]
## Description

Rayleigh damping in physics isn't used with fv3atm, because the dycore handles it. The CCPP scheme `rayleigh_damp` returns immediately if certain conditions are met, and these are true for all ufs-weather-model runs:
```
if (lsidea .or. ral_ts <= 0.0 .or. prslrd0 == 0.0) return
```

PR https://github.com/NOAA-EMC/fv3atm/pull/303 removes `rayleigh_damp` from a handful of suite definition files. We should remove it from all other suite definitin files, too.

**Comment by junwang-noaa** [comment]
The code was merged, close issue.

**Comment by climbfuji** [comment]
Sorry, the calls to `rayleigh_damp` were removed from a handful of suites as per description above, it is still in most of the suites. Reopening.
