### ISSUE TITLE
ZERO surface albedo and ZERO surface upward shortwave flux outputs

### ISSUE THREAD

**Issue by wzzheng90** [NOAA-EMC/ufsatm#343]
## Description
UFS P7b includes ZERO surface albedo and ZERO surface upward shortwave flux outputs.

Need to check if this issue is just for a post-process problem or problems related to physics schemes too.

### To Reproduce:
What compilers/machines are you seeing this with?
Give explicit steps to reproduce the behavior.
1. do this
2. then that
3. then, oops, look at the bug

## Additional context
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- needs to be fixed also in noaa-emc/nems/issues/<issue_number>
- needed for noaa-emc/fv3atm/pull/<pr_number>

## Output

**Screenshots**
If applicable, drag and drop screenshots to help explain your problem.

**output logs**
If applicable, include relevant output logs.
Either drag and drop the entire log file here (if a long log) or

```
paste the code here (if a short section of log)
```

## Testing:

1. Have you tested the code changes? On what platforms?

2. Have you run regression test in ufs-weather-model or ufs-s2s-model with code changes?
- Will the baseline results change? 
- If the baseline results change, is it expected? Please give brief explanation.

## Dependent PRs:

Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/GFDL_atmos_cubed_sphere/issues/<issue_number>
- ncar/ccpp-physics/pull/<pr_number>
- associated ufs-weather-model/pull/<pr_number>

**Comment by yangfanglin** [comment]
But the albedo scattering plot Lydia showed at the coupled model meeting today  have values

**Comment by wzzheng90** [comment]
Good point.  I need to double-check it if I use the same model outputs as Lydia.

**Comment by wzzheng90** [comment]
This issue was identified. Zero values occur from the checked version and are related to regression test script "rt_35d.conf". 
The original case selection "cpld_bmark_wave_v16_noahmp_35d" was changed to "cpld_bmark_wave_v16_p7b_35d" now.  So, this PR is closed now and no further action is taken.
