### ISSUE TITLE
change nbit for delp compression in netcdf output

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-EMC/ufsatm#36]
Currently fv3 is using one single variable nbit for the compression of 3D model output fields. It turns out that the nbit(14 in fv3 parallel) could cause delp field to loose required precision, especially when delp is small in high altitude. Fanglin made a quick fix to use different nbit for delp field. This fix is planned to be used in GFSv16 implementation.

**Comment by jswhit** [comment]
I thought this issue was resolved by fixing the helicity calculation in the post-processor?

**Comment by jswhit** [comment]
Also, since ps is not truncated before compression, the fully accurate delp can be reconstructed from ps, a_k and b_k.

**Comment by junwang-noaa** [comment]
Jeff,
Please see Anning's email below:

I just noticed that the calculation of pmid in the post has used hydrostatic approximation, which is not consistent the non-hydrostatic assumption:

pmid(i,j,l)=rgas*dpres(i,j,l)* &
                t(i,j,l)*(q(i,j,l)*fv+1.0)/grav/abs(buf3d(i,j,l)) 

In above formula, rou = delp/g/delz  use hydrostatic assumption. In addition to its unphysical issue, the dz<1.e-4 is direclty caused by the wrongly calculated pmid as I showed in the attached file in my first email, i.e.,pPmid(118) should have a value between pint(118) and pint(199), but Pmid(118) is smaller than any of them.  

The only cure is output pmid directly.  We have now outputed the following related variables in netcdf:
pfull(pfull),  phalf(phalf),  delz(time, pfull, grid_yt, grid_xt), hgtsfc(time, grid_yt, grid_xt), dpres(time, pfull, grid_yt, grid_xt), and pressfc(time, grid_yt, grid_xt). 
The last four variables are used to calculate zint and pint. One more variable output,  such as pmid(time, pfull, grid_yt, grid_xt)   will give reasonable zmid( time, ppull, grid_yt, grid_xt ), d/dz, helicity, N^2, and Richardson number etc. even with the lose of accuracy of p, t, and moisture. 

Happy holidays,

Anning

**Comment by jswhit** [comment]
I interpreted that to mean problem solved without extra precision - but maybe I'm not understanding.

**Comment by junwang-noaa** [comment]
My understanding is that the fix is made from Anning's suggestion and is tested in fv3 parallel. I may miss something since I was off the last couple of days. I am including @yangfanglin and @AnningCheng-NOAA in this ticket for comments.

**Comment by yangfanglin** [comment]
Jeff:   Deriving pmid as averages of interfacing layer pressures does seem to solve all the problems.   However, the latest investigations are all based on the model output without delp compression.  We need to check again if there is still any issue with helicity computation and analysis increments etc if delp is compressed.  Given that the model sometimes tends to produce every thin layers, I'd suggest we do not compress delp.   If Jun needs to make a commit soon,  I recommend Jun can go ahead with the current mods.  We can revert the change after more test is done.

**Comment by yangfanglin** [comment]
Wen Meng ran the latest UPP, which computes pmid as averages of interfacing layer pressures instead of using the  hydrostatic equation,  with compressed netCDF history files (including delp).  The odd features did not resurface.   So we can revert back to apply the same compression (nbits=14) to all variables in the history file.

**Comment by junwang-noaa** [comment]
The issue is resolved by computing pmid as averages of interfacing layer pressures instead of using the hydrostatic equation, the change is committed in pull request #48 GFSv16 netcdf post ficein cpl, close ticket.

**Comment by AnningCheng-NOAA** [comment]
Thanks! Jun
