### ISSUE TITLE
ice fraction needs to be truncated to values < 1.0

### ISSUE THREAD

**Issue by DeniseWorthen** [NOAA-EMC/ufsatm#38]
When running in coupled mode, the ice fraction imported from the mediator can be greater than 1. This is non-physical and results in a seg fault when the (1-fice) is used to calculate the surface stress3.  

In atmos_model, the imported ice fraction needs to be bounded to be strictly between zero and one:

IPD_Data(nb)%Coupling%ficein_cpl(ix) = max(zero,min(datar8(i,j),one))

This is a bugfix and is expected to change answers in the coupled model but have no impact on standalone.

**Comment by junwang-noaa** [comment]
Code is committed, close issue.
