### ISSUE TITLE
decrease of memory usage of MERRA2 data by 6 times

### ISSUE THREAD

**Issue by AnningCheng-NOAA** [NOAA-EMC/ufsatm#420]
## Description
Provide a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
The 12 months of MERRA2 data is read in for interpolation, which use large memory
## Solution
Add a clear and concise description of what solution you provide.
A way is found to read in only 2 months of data and saves the memory usage

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Testing:

1. Have you tested the code changes? On what platforms?
2. Have you run regression test in ufs-weather-model or ufs-s2s-model with code changes?
- Will the baseline results change?
- If yes, please give brief explanation of your code updates on the regression test.

## Dependent PRs:

Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/GFDL_atmos_cubed_sphere/issues/<issue_number>
- ncar/ccpp-physics/pull/<774>
- associated ufs-weather-model/pull/<903>

**Comment by DeniseWorthen** [comment]
@AnningCheng-NOAA I believe this issue has been fixed a long time ago? If so, please close the issue.

**Comment by AnningCheng-NOAA** [comment]
@DeniseWorthen, yes it was resolved  a long time ago. Closed.
