### ISSUE TITLE
Semi Lagrangian sedimentation of graupel and update of corresponding namelist variables

### ISSUE THREAD

**Issue by RuiyuSun** [NOAA-EMC/ufsatm#427]
## Description
The semi-Lagrangian sedimentation of graupel is added. The namelist variables controlling the semi-Lagrangian sedimentation of precipitation (rain and graupel) are modified. Now SEDI_SEMI and DECFL is the switch. DECFL is the deformed CFL factor.

Semi-Lagrangian sedimentation of precipitation is added as an option and does not change results before it is turned on.

## Testing:
The code change has been tested on Hera by using one RT test. The change doesnot change the baseline. 

## Dependent PRs:

Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/GFDL_atmos_cubed_sphere/issues/<issue_number>
[- ncar/ccpp-physics/pull/<pr_number>](https://github.com/NCAR/ccpp-physics/pull/770)
[- associated ufs-weather-model/pull/<pr_number>](https://github.com/ufs-community/ufs-weather-model/pull/923)

**Comment by climbfuji** [comment]
@RuiyuSun I merged ccpp-physics - please update the submodule pointer and revert `.gitmodules`, new ccpp-physics hash is c3627d9 . Thanks!

**Comment by DeniseWorthen** [comment]
@RuiyuSun It looks like this issue was fixed a long time ago? If so, we need to close this issue.

**Comment by RuiyuSun** [comment]
I think it is. Please close it.
