### ISSUE TITLE
Zero net longwave sent to ocean

### ISSUE THREAD

**Issue by SMoorthi-emc** [NOAA-EMC/ufsatm#429]
## Description
Provide a clear and concise description of what the bug is.
Also give a description of how to fix the bug.
The net long wave radiation received in the ocean model has zero value everywhere.
The fix is to remove initializing  the interstitial variable semis_water in GFS_typedefs.F90

### To Reproduce:
What compilers/machines are you seeing this with?
Give explicit steps to reproduce the behavior.
1. do this
2. then that
3. then, oops, look at the bug
Just run coupled model and look at ocean history file.

## Additional context
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- needs to be fixed also in noaa-emc/nems/issues/<issue_number>
- needed for noaa-emc/fv3atm/pull/<pr_number>
This issue was first reported by Ufuk Turuncoglu.

## Output

**Screenshots**
If applicable, drag and drop screenshots to help explain your problem.

**output logs**
If applicable, include relevant output logs.
Either drag and drop the entire log file here (if a long log) or

```
paste the code here (if a short section of log)
```

## Testing:

1. Have you tested the code changes? On what platforms?
Yes, on WCOSS DELL.
2. Have you run regression test in ufs-weather-model or ufs-s2s-model with code changes?
No
- Will the baseline results change? 
- Yes
- If the baseline results change, is it expected? Please give brief explanation.
- Currently, the net longwave at water surface is zero.  When this is fixed results will change and so does the baseline. 

## Dependent PRs:

Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/GFDL_atmos_cubed_sphere/issues/<issue_number>
- ncar/ccpp-physics/pull/<pr_number>
- associated ufs-weather-model/pull/<pr_number>

**Comment by junwang-noaa** [comment]
The code updates to fix the issue was committed in PR #434. Issue is closed.
