### ISSUE TITLE
Move deprecated suite definition files (SDFs) into a 'untested' subdirectory 

### ISSUE THREAD

**Issue by ChunxiZhang-NOAA** [NOAA-EMC/ufsatm#510]
## Description
Many suite definition files (SDFs) are no longer supported by regression tests (RTs). Therefore, there are high risks that those SDFs will encounter errors when used in applications. We decided to move those SDFs into a 'untested' subdirectory under the ccpp/suites directory. Users can modify and test those deprecated SDFs.  

**The SDFs that will be saved are:**
FV3_GFS_v17_p8
FV3_GFS_v17_p8_rrtmgp
FV3_GFS_v17_coupled_p8
FV3_GFS_v17_coupled_p8_sfcocn
FV3_GFS_v15p2
FV3_GFS_v15_thompson_mynn_lam3km
FV3_GFS_v16
FV3_GFS_v16_csawmg
FV3_GFS_v16_ras
FV3_GFS_v16_fv3wam
FV3_RAP
FV3_RAP_RRTMGP
FV3_RAP_sfcdiff
FV3_RAP_unified_ugwp
FV3_RAP_cires_ugwp
FV3_RAP_flake
FV3_RAP_noah
FV3_RAP_noah_sfcdiff_cires_ugwp
FV3_HRRR
FV3_HRRR_smoke
FV3_RRFS_v1beta
FV3_RRFS_v1nssl
FV3_WoFS_v0
FV3_HAFS_v1_gfdlmp_tedmf
FV3_HAFS_v1_gfdlmp_tedmf_nonsst
FV3_HAFS_v1_thompson_tedmf_gfdlsf
FV3_HAFS_v1_thompson_noahmp_nonsst
FV3_HAFS_v1_thompson_noahmp
FV3_HAFS_v1_thompson_nonsst
FV3_HAFS_v1_thompson

**Those 4 SDFs are compiled but not in any RTs**
FV3_GFS_cpld_rasmgshocnsstnoahmp_ugwp
FV3_GFS_v15_thompson_mynn
FV3_GFS_v16_ugwpv1
FV3_GFS_v16_noahmp

**Comment by BrianCurtis-NOAA** [comment]
I know AQM current RT's use v15p2, but they will soon be moved to v16. I'm not sure what other suites use v15p2, in case AQM was the only RT keeping that in the list.

**Comment by ChunxiZhang-NOAA** [comment]
@BrianCurtis-NOAA @DusanJovic-NOAA @DeniseWorthen @junwang-noaa @jkbk2004 @yangfanglin I updated the list for the SDFs that are tested in RTs. There are only 29 of them.  Please let me know if I missed any SDF.

**Comment by DusanJovic-NOAA** [comment]
`FV3_GFS_v16_fv3wam` is used by control_wam and control_wam_debug tests.

**Comment by ChunxiZhang-NOAA** [comment]
@DusanJovic-NOAA Good catch. I've added it into the list.
