### ISSUE TITLE
error in single time-step physics output

### ISSUE THREAD

**Issue by pjpegion** [NOAA-EMC/ufsatm#530]
## Description
I am running the model, writing history every time-step. Even though I am setting fhzero to the output interval, in my case I am running with 720 seconds, so fhzero is 0.2.  But the logic in CCPP_driver results in phys_zero to never being called.  

I am Proposing changing
if (mod(GFS_control%kdt,GFS_control%nszero) == 1) then
to
if ((mod(GFS_control%kdt-1,GFS_control%nszero)+1) == 1) then

It fixes the 1 time-step problem, and I am running a limited number of regression tests right now to see if it changes the answer.

**Comment by junwang-noaa** [comment]
@pjpegion maybe the title can be more specific, e.g.  "error in single time-step physics output when fhzero=dtp".

**Comment by DusanJovic-NOAA** [comment]
Fixed in #531
