### ISSUE TITLE
Create a working version of fv3atm with ccpp release-v6 for use with the SRW release/public-v2

### ISSUE THREAD

**Issue by mark-a-potts** [NOAA-EMC/ufsatm#547]
The SRW needs a version of the ufs-weather-model that uses version 6 of CCPP. This release branch of fv3atm will be used in the corresponding release branch of ufs-weather-model that will be used by the SRW in its release/public-v2.

**Comment by junwang-noaa** [comment]
The code is merged, the issue will be closed.
