### ISSUE TITLE
redefining ice fraction in FV3 as ratio of ice area to ocean area

### ISSUE THREAD

**Issue by ShanSunNOAA** [NOAA-EMC/ufsatm#64]
To commit 3 code changes needed when redefining ice fraction in FV3 as ratio of ice area to ocean area:

atmos_model.F90
io/FV3GFS_io.F90
gfsphysics/GFS_layer/GFS_physics_driver.F90 

It has passed control regression test.

**Comment by junwang-noaa** [comment]
@shansun6 This was fixed, can we close the issue?

**Comment by ShanSunNOAA** [comment]
Yes, please. I looked and didn't find the close button.

Shan
