### ISSUE TITLE
fixes in gfdl_cloud_microphys.F90 to reduce the cold bias in lower atmosphere layer

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-EMC/ufsatm#7]
The  gfdl_cloud_microphys.F90 is udpated to reduce the cold bias in lower atmosphere layer.  A new variable 'qmin1' was added to determine when reimin and resmin will be used. The qmin1 uses the original value from GFSv15.

**Comment by RuiyuSun** [comment]
It looks fine to me.

**Comment by junwang-noaa** [comment]
The code was committed, close the issue.
