### ISSUE TITLE
new canopy heat storage parameterization (CHSP) scheme

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-EMC/ufsatm#70]
A new canopy heat storage parameterization (CHSP) scheme is ready with bug fixes from previous version.

**Comment by JongilHan66** [comment]
The new CHSP has been developed and it is a bug free and has no the residual issue:
1) Unlike the old CHSP, CHS is now achieved somewhat explicitly by reducing input surface sensible and latent heat fluxes to the PBL scheme as a function of surface roughness (z0).
2) there are no changes in Noah LSM and Noah MP associated with the new CHSP, except that the current urban heat storage parameteriztion in Noah LSM is replaced with the new CHSP if the new CHSP is defined as .true.
3) considering ventilation effect by wind, full CHSP for wind speed at 10m (U10) < 2.5m/s; no CHSP for U10 > 7.5 m/s, linear decrease of CHSP for 2.5 m/s < U10 < 7.5 m/s.
4) the new CHSP shows a reasonably good reduction of diurnal variation of T2m over large z0 for weak wind condition.

The updated files for the new CHSP are:

GFS_physics_driver.F90: physics driver
sfc_drv.f, sflx.f : Noah LSM
sfc_noahmp_drv.f, module_sf_noahmplsm.f90 : NoahMP

which can be found in /scratch1/NCEPDEV/global/Jongil.Han/save/git/fv3gfs/gfsv16b/sorc/fv3gfs.fd/FV3/gfsphysics/tmp on Hera.  If  lheatstrg=.false., the CHSP is not applied and the control result doesn't change.

A longer longer term (1/1-2/18, 2020) result from the new CHSP can be found in

https://www.emc.ncep.noaa.gov/gmb/jhan/vsdbw/v16ml10i9chsqv/

v16ml10if09nhst: without CHSP
v16ml10i9chsqv: with new CHSP

The new CHSP show that
1) The 500mb height AC is improved for both NH and SH especially in later forecast hours (i.e., from 144 FH [6 day]). This is an encouraging result, considering the parallel run (v16rt2) degrades the 500mb height AC for NH in later FH starting from 144 FH.
2) Impact on precip score looks neutral.
3) Wind vector RMSE indicates a degrade near tropopause.
4) The new CHSP yields a little warmer T2m & Tsfc.
5) For the grid-to-obs analysis, the impact of the CHSP looks quite small. One good impact is a reduction of T2m cold bias over Alaska.

**Comment by JongilHan66** [comment]
Fraction factor parameters for CHSP (z0fac & e0fac) are now defined in 
    GFS_typedefs.F90, which is also placed in /scratch1/NCEPDEV/global/Jongil.Han/save/git/fv3gfs/gfsv16b/sorc/fv3gfs.fd/FV3/gfsphysics/tmp

Accordingly, GFS_physics_driver.F90 is modified.

**Comment by junwang-noaa** [comment]
Committed. Close issue.
