### ISSUE TITLE
Update cellular automata code and coupling

### ISSUE THREAD

**Issue by lisa-bengtsson** [NOAA-EMC/ufsatm#71]
The cellular automata (CA) code is updated so that several CA's can run on the FV3 grid and the sub-grid simultaneously. The coupling to the SASAS convection scheme is updated to address uncertainty associated with entrainment when convection becomes more organized. The capability of running SPPT with a pattern generated from cellular automata (instead of AR(1)) is added.  

The updates concern the submodules: fv3atm and stochastic_physics

**Comment by DusanJovic-NOAA** [comment]
@lisa-bengtsson Is this issue resolved by one of the already merged PR's?

**Comment by lisa-bengtsson** [comment]
> @lisa-bengtsson Is this issue resolved by one of the already merged PR's?

Yes, this was the big commit we worked on back in spring.
