### ISSUE TITLE
possible memory leak in fv3

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-EMC/ufsatm#72]
In the coupled s2s model, it is found that the fv3 memory is increasing every 6hour for the first 2 days, then the memory increases slightly for the rest of forecast time. This may indicate a memory leak problem in fv3 component, further investigation is needed.

**Comment by climbfuji** [comment]
@junwang-noaa is this still the case?

**Comment by junwang-noaa** [comment]
We don't have a chance to retest this one with the develop branch.

**Comment by junwang-noaa** [comment]
The major memory issue in fv3atm was fixed in stochastic physics [PR#45](https://github.com/noaa-psd/stochastic_physics/pull/45), close issue.
