### ISSUE TITLE
merge code changes in public release back to develop branch

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-EMC/ufsatm#73]
When public release branch is finalized, the hot fixes in public release branch needs to be merged to develop branch.

The code changes include:

fv3atm github pull request:
1. Add no_nsst CCPP suites (htps://github.com/NOAA-EMC/fv3atm/pull/69)
2. release/public-v1: bug fix for threading issue in stochastic physics (htps://github.com/NOAA-EMC/fv3atm/pull/62)
3. ufs_public_release: remove libxml2. (htps://github.com/NOAA-EMC/fv3atm/pull/55)
4. Fix dependencies for fv3cap library (htps://github.com/NOAA-EMC/fv3atm/pull/45)
5. make variables using filename_base consistant in length (htps://github.com/NOAA-EMC/fv3atm/pull/43)
6. Set default calendar to 'gregorian' (htps://github.com/NOAA-EMC/fv3atm/pull/34)
7. Remove unused and unsupported code (htps://github.com/NOAA-EMC/fv3atm/pull/31)

**Comment by climbfuji** [comment]
@junwang-noaa I think we did all that a long time ago, shall we close the issue?

**Comment by junwang-noaa** [comment]
Yes, we can close this one.
