### ISSUE TITLE
Is anyone using the doxygen documentation partially implemented in fv3atm?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/ufsatm#754]
## Description
The fv3atm is going through a documentation update. There are currently some doxygen artifacts in the code. Are these being used by anyone? Or are they artifacts of code taken from somewhere else?

For example in io/fv3atm_clm_lake_io.F90 we have:

```
  !>\defgroup CLM Lake Model restart public interface
  !>  @{

  !>@ The clm_lake_data_type derived type is a class that stores
  !!  temporary arrays used to read or write CLM Lake model restart
  !!  and axis variables. It can safely be declared and unused, but
  !!  you should only call these routines if the CLM Lake Model was
  !!  (or will be) used by this execution of the FV3. It is the
  !!  responsibility of the caller to ensure the necessary data is in
  !!  Sfc_restart, Sfcprop, and Model.
  type clm_lake_data_type

```

This defines a doxygen group. Is anyone using this?

## Solution
If this is part of a larger documentation set, we must ensure that our upcoming documentation efforts don't break that.

If these are left-over artifacts in the code, then we can remove them, if they don't make sense.

## Alternatives
We are open to any alternative which allows us to improve the fv3atm documentation, without breaking anything else.

**Comment by ligiabernardet** [comment]
@mzhangw Bringing this to your attn

**Comment by mzhangw** [comment]
add @SamuelTrahanNOAA

**Comment by SamuelTrahanNOAA** [comment]
That documentation block is correct. If you desire a different documentation format, it should be converted to that format.

I'm not sure if I wrote that or someone else. If it was me, then I was mimicking the CCPP documentation blocks, since I had no other reference to work from.

**Comment by edwardhartnett** [comment]
OK, thanks. We will preserve all this documentation, but will feel free to adjust the format details to make the fv3atm documentation build work well...
