### ISSUE TITLE
can't clone FV3 on orion

### ISSUE THREAD

**Issue by DeniseWorthen** [NOAA-EMC/ufsatm#758]
## Description

I attempted to clone ufs-weather-model on orion but had a problem in FV3 so I tried instead to clone just FV3. 

``git clone https://github.com/NOAA-EMC/fv3atm.git``

I got 

```
....
Submodule path 'ccpp/physics': checked out 'a492addf860d29d797bca488f53d39b260584924'
error: invalid key (newline): submodule.physics/rte-rrtmgp
physics/Radiation/RRTMGP/rte-rrtmgp.url
error: invalid key (newline): submodule.physics/rte-rrtmgp
physics/Radiation/RRTMGP/rte-rrtmgp.url
No url found for submodule path 'physics/Radiation/RRTMGP/rte-rrtmgp' in .gitmodules
Cloning into 'upp'...

etc

```

**Comment by DeniseWorthen** [comment]
@dustinswales Do you have any ideas? Or @jkbk2004 Are we sure we merged Anning's PR correctly?

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen I ran into this issue earlier today with global-workflow.  If you do "module load git" it will update your version of git and then the ufs-weather-model will clone as expected.

**Comment by jkbk2004** [comment]
can you try to use git/2.28.0? I have no issue on orion.

**Comment by DeniseWorthen** [comment]
Thanks, both you. Why is this an issue? Why do users have to constantly "fix" their git module on orion?

**Comment by DeniseWorthen** [comment]
I'll close this issue. I think Orion is the *only* platform where I've run into issues having to update the version of git I'm using.
