### ISSUE TITLE
Model uses constant SST, different from SST forcing file

### ISSUE THREAD

**Issue by oliverwm1** [NOAA-EMC/ufsatm#79]
The output surface temperature (`tsfc`) over ocean is constant in time, despite using `  RTGSST.1982.2012.monthly.clim.grb` which depends on month. Is this expected behavior? When doing the same run with the [previous public release source code](https://github.com/NOAA-EMC/fv3gfs), the surface temperature over the ocean tracks much closer to the SST forcing file, as I would expect. 

The figure below plots the monthly-mean `tsfc` (left panel) and `t2m` (right panel). Output is shown from a run with the source code of this repo (fv3atm) and the previous public release (fv3gfs). Data from the SST forcing file is also shown for the surface temperature plot.

![tsfc_t2m_2016](https://user-images.githubusercontent.com/23640870/76543377-aad69f00-6443-11ea-896f-cdbf89704466.png)

Possibly related: I notice in the code, `tsfc` is [described as the surface air temperature in a comment](https://github.com/NOAA-EMC/fv3atm/blob/fc9a4c215b12061f22866c83bf251e1385644f1e/gfsphysics/GFS_layer/GFS_typedefs.F90#L228). Is that accurate?

Thanks for any guidance you can provide!

**Comment by junwang-noaa** [comment]
It depends on how the model is configured. Can you check what the "FHCYC" in your model namelist is set with?

**Comment by oliverwm1** [comment]
Thanks for the response! `fhcyc` is set to 24.0. You can find the complete namelist I used for the simulation above [here](https://gist.github.com/oliverwm1/5b27b5f708f8cae24e3f5776e5289332).

**Comment by spencerkclark** [comment]
@junwang-noaa have you had a chance to investigate this further?  Are there settings we are missing and/or does this issue exist with the current version of fv3atm?  

In our fork -- which is a little behind the latest version here -- adding the following above [these lines](https://github.com/NOAA-EMC/fv3atm/blob/90bc1a4d6b660b5497c36dc009e1624f9982a2b1/gfsphysics/GFS_layer/GFS_physics_driver.F90#L1159-L1163) appears to fix things:
```
          if (islmsk(i) == 0) then
            Sfcprop%tsfco(i) = Sfcprop%tsfc(i)
            wet(i)  = .true.
            fice(i) = zero
```
As far as I can tell, without it, over ocean grid cells `tsfco` remains at its value from the initial condition throughout the entire simulation.  This change allows it to be updated as `tsfc` is relaxed to the climatological SST over ocean.  Could this be the correct solution, or is there a reason it was originally commented out and eventually removed altogether?

**Comment by junwang-noaa** [comment]
Sorry, I have not gotten time to check this. I just checked your code
changes, it makes sense to me. What I see is that the if statement should
be added to pass the updated tsfc on ocean points from gcycle to tsfc3 in
gfs physics driver. I may need to double check with our physics experts.

**Comment by spencerkclark** [comment]
Indeed I think another way to fix this would be to switch `tsfco` to `tsfc` here:

https://github.com/NOAA-EMC/fv3atm/blob/90bc1a4d6b660b5497c36dc009e1624f9982a2b1/gfsphysics/GFS_layer/GFS_physics_driver.F90#L1242

Keep us posted on what you think / what the physics experts say.  Thanks again for your help!

**Comment by junwang-noaa** [comment]
The sst issue appears fixed in the latest develop branch. Here is what I get from the fv3 control run. The point is (179W, 45N)

**Comment by junwang-noaa** [comment]
![image](https://user-images.githubusercontent.com/37633869/110166032-c576f600-7dc1-11eb-8230-57859620a850.png)

**Comment by junwang-noaa** [comment]
Close the issue.

**Comment by spencerkclark** [comment]
Excellent, thanks @junwang-noaa!  Would you happen to know the particular commit (or change) that fixed this?

**Comment by junwang-noaa** [comment]
I did not track the issue with each commit, but I think it is the FV3 PR#155
<https://github.com/NOAA-EMC/fv3atm/pull/155> and  PR #204
<https://github.com/NOAA-EMC/fv3atm/pull/204>.

**Comment by oliverwm1** [comment]
Thanks @junwang-noaa!
