### ISSUE TITLE
CI no longer working?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/ufsatm#820]
The CI is failing like this:

```
/home/runner/work/fv3atm/fv3atm/fv3atm/ccpp/framework/src/ccpp_types.F90:22:9:

   22 |     use mpi_f08, only: MPI_Comm
      |         1
Fatal Error: Cannot open module file ‘mpi_f08.mod’ for reading at (1): No such file or directory
compilation terminated.
```

@AlexanderRichert-NOAA any idea why this is happening?

**Comment by AlexanderRichert-NOAA** [comment]
Hm not offhand. It's using a cached copy of mpich (which is built through Spack), so it's possible but unlikely that  mpi_f08.mod would be randomly missing... I'm not sure why this would be happening "suddenly," but it might be worth explicitly setting "CMAKE_C_COMPILER=mpicc" and "CMAKE_Fortran_COMPILER=mpifort". If that doesn't work, you could look at the output of `find $(spack location --install-dir mpich)` right before the cmake call just to confirm that mpi_f08.mod is present, plus `make VERBOSE=1` to confirm that there's an appropriate '-I' entry for that module.

Also clearing the cache is my go-to "turn it off and back on" solution...

**Comment by AlexanderRichert-NOAA** [comment]
Addendum: I just tried installing mpich@3.4.3 with Spack on my personal machine and there's also no mpi_f08.mod, so I have to imagine that's related. I'll look into why it's missing (or maybe it was never there?).

**Comment by AlexanderRichert-NOAA** [comment]
Likely culprit: https://github.com/NCAR/ccpp-framework/blob/011db4f80a02cba6d65958ace56e8efb197be62b/src/ccpp_types.F90 (the ccpp framework submodule was updated in fv3atm a couple weeks ago)
I'm betting `#define MPI` wasn't set before so it wasn't using the `use mpi_f08.mod` previously...

**Comment by DusanJovic-NOAA** [comment]
It will be fixed in this PR https://github.com/NOAA-EMC/fv3atm/pull/805

**Comment by AlexanderRichert-NOAA** [comment]
:+1: looks like any mpich@4.x will provide mpi_f08.mod...

**Comment by edwardhartnett** [comment]
@junwang-noaa and @DusanJovic-NOAA the settings on this repo should be set so that no PR which breaks CI can be merged.

![image](https://github.com/NOAA-EMC/fv3atm/assets/38856240/d680c2a4-e9ab-45c2-b7a1-ae39d7b077f5)

**Comment by DusanJovic-NOAA** [comment]
Fixed in #811

**Comment by edwardhartnett** [comment]
@DusanJovic-NOAA have repo settings been changed to prevent recurrence?

**Comment by DusanJovic-NOAA** [comment]
I didn't change anything but I see those two settings are already selected.
