### ISSUE TITLE
Write output in subdirectory `FV3ATM_OUTPUT/`

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/ufsatm#822]
## Description
The write grid component model output is controlled via `model_configure`.  Specifically, this line in `model_configure` is used to generate the `atm` and `sfc` files:
```
filename_base: 'atm' 'sfc'
```
By default, this output of `atmf000.nc`, `atmf003.nc`, ... and, `sfcf000.nc`, `sfcf003.nc`, ... are created at the root of the run directory.
The FV3ATM component also allows the running of inline UPP.  Inline-post produces `GFSPRS.FHH` and `GFSFLX.FHH` files.  

This issue requests a feature so that this output can be created under a sub-directory e.g. `FV3ATM_OUTPUT/`.  Doing so has several advantages:
- At long forecast hours, the output volume overwhelms the run directory and saving output in a component specific sub-directory will aid in better organizing data and diagnosing issues in the event of model failures
- The workflows can redirect these output to a common path allowing restart capabilities from failure to continue.
- The FV3 output will be consistent w/ other components e.g. MOM6 and CICE6 that allow placing their output in similar sub-directories `MOM6_OUTPUT/` and `CICE_OUTPUT/`. These paths are namelist controlled and the defaults are `./`

## Solution
Allow FV3 output from the write grid component be created under `FV3ATM_OUTPUT/` (or some path) controlled via namelist or `model_configure`.

## Alternatives
I created a sub-directory named `FV3ATM_OUTPUT/` in the run directory and then I tried the following in `model_configure`:
```
filename_base: 'FV3ATM_OUTPUT/atm' 'FV3ATM_OUTPUT/sfc'
```

The model failed to in the IO component.

This would not solve the inline post output part of the issue.

## Testing:
- Will the baseline results change?  No.  Baselines should not change due to change in output path

## Dependent PRs:

May need a change in UPP to allow placing of `GFSPRS` and `GFSFLX` files in sub-directory.

**Comment by DusanJovic-NOAA** [comment]
Please take a look at this branch (https://github.com/DusanJovic-NOAA/fv3atm/tree/fv3atm_output_dir) and test it to make sure everything works as expected. Corresponding ufs-weather-model branch is https://github.com/DusanJovic-NOAA/ufs-weather-model/tree/fv3atm_output_dir

**Comment by aerorahul** [comment]
Thanks @DusanJovic-NOAA 
I will give this a try ASAP in the atm-only mode, however, we won't be able to use this until some other issues in the model/workflow get sorted out.
