### ISSUE TITLE
negative precipitation with stochastic physics when coupled

### ISSUE THREAD

**Issue by pjpegion** [NOAA-EMC/ufsatm#84]
Currently, there may be negative rain or snow being passed to the ocean and ice when SPPT is enabled. This is because of the inconsistency between the partitioning of the rain/snow and the rain/snow tendency.

The fix requires modifications to ccpp_physics: FV3/ccpp/physics/physics/GFS_MP_generic.F90  There will also be a separate pull request for the IPD side. This is related to
https://github.com/ufs-community/ufs-s2s-model/issues/58
Phil

**Comment by climbfuji** [comment]
@pjpegion I believe this issue has been solved. Please check and if so, close it. Thanks!
