### ISSUE TITLE
dyn_core fails when SKEB is true and d_con is zero

### ISSUE THREAD

**Issue by NeilBarton-NOAA** [NOAA-EMC/ufsatm#860]
## Description
The model fails when d_con is zero and skeb is True because heat_source is unallocated. This change allocates heat_source when skeb is True. PR submitted and approved in GFDL_atmos_cubed_sphere

https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/351 

### To Reproduce:
set SKEB to T and d_con to zero, and the ATM model will fail. Found when running ensembles in hydrostatic mode on hera using intel compilers. 

## Additional context

No issue previously assigned. 

This change is needed to run SFS ensembles, is  one-line change, and is currently not tested in the RTs. Adding this change to another PR for a quick inclusion to ufs-weather-model would be ideal for the SFS testing. 
 
PR submitted and approved in GFDL_atmos_cubed_sphere

https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/351 

## Output

change is at line 386 in dy_core.F90

```
    if ( flagstruct%d_con > 1.0E-5 ) then
    if ( flagstruct%d_con > 1.0E-5 .OR. flagstruct%do_skeb) then
```

## Testing:

1. Have you tested the code changes? On what platforms?
Code has been tested in g-w on hera. 

2. Have you run regression test in ufs-weather-model or ufs-s2s-model with code changes?
RT testing in process, no expected changes in baselines.

**Comment by pjpegion** [comment]
@NeilBarton-NOAA I just found this too, that for finding the fix.
