### ISSUE TITLE
Missing change in CCPP physics

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/ufsatm#9]
The recent merge of https://github.com/NOAA-EMC/fv3atm/pull/8 contained a small change in GFS_physics_driver.F90 that was not made in CCPP. This PR addresses it: https://github.com/NCAR/ccpp-physics/pull/353

**Comment by junwang-noaa** [comment]
This code is committed in https://github.com/NCAR/ccpp-physics/pull/353, close issue.
